### ISSUE TITLE
Invalid autogenerated 'symbol' regex pattern

### ISSUE THREAD

**Issue by rhumbertgz** [langium/langium-minilogo#10]
Hi, 

After  executing the "langium:generate" script a new [minilogo.monarch.ts](https://github.com/langium/langium-minilogo/blob/main/syntaxes/minilogo.monarch.ts) is generated with invalid _symbol_ regex pattern.

The original regex pattern found in this repo:
`symbols:  /-|,|\(|\)|\{|\}|\*|\/|\+|=/,`

The new generated regex pattern:

`symbols:  /\(|\)|\*|\+|,|-|/|=|\{|\}/,`

The image below shows the current error

![Screenshot 2023-07-05 at 16 47 17](https://github.com/langium/langium-minilogo/assets/10393245/8b492ed1-28d7-4a26-81ea-65f7510beffb)

I'm running the same langium version, even using the package-lock.json. Langium should generate a valid regex pattern.

**Comment by msujew** [comment]
Closing, please continue the discussion in https://github.com/langium/langium/issues/740.
