### ISSUE TITLE
Cannot start web ide

### ISSUE THREAD

**Issue by borzi** [langium/langium-minilogo#11]
Dear team!

First of all I love the langium, and I think it is a really cool projects, and big thanks. Unfortunately I have some issues with this example.

I tried to start the repo locally, but I have lots of errors.

First there is no `npm run build` command now, but the readme contains this.

Second I cannot run locally the web editor based on the newest commit. I got error from the web: ncaught SyntaxError: The requested module './monaco-editor-wrapper/index.js' does not provide an export named 'vscode' (at setup.js:1:45). 

I can start the web server based on a previous commit (ea44d9, editor immage) and that works fine.

Could you fix the repo readme, and give a step by step guide that works?

**Comment by montymxb** [comment]
Hi @borzi , glad to hear you're enjoying Langium!

I can take a look and see if we missed something in the recent change. Most likely I overlooked something between commits, and need to go back to verify the behavior. As for the README thanks for pointing out the inconsistency, I can take a peek at that we as well and correct it.

**Comment by montymxb** [comment]
Hey @borzi , this should be resolved with the addition of #12 , which reset the pre-existing dev-packages we were using before. That should bring the repo back in line with the readme & previous dev setup (like local testing in a web page).

We will upgrade this dev setup at a later point in time, but for now this will keep things as they were before.

**Comment by borzi** [comment]
Hello @montymxb !

Thanks for the update, I tried it, and it works fine!

Have a nice day :)
