### ISSUE TITLE
Langium MiniLogo example doesn't build:

### ISSUE THREAD

**Issue by steve-hickman-epistimis** [langium/langium-minilogo#3]
Attempt to build the MiniLogo example failed because a static file is missing

``
Epistimis-Laptop:langium-minilogo stevehickman$ ./bin/cli generate examples/test.logo
node:fs:600
 handleErrorFromBinding(ctx);
 ^

Error: ENOENT: no such file or directory, open './src/static/mini-logo.js'
   at Object.openSync (node:fs:600:3)
   at Object.readFileSync (node:fs:468:35)
   at /Users/stevehickman/Documents/GitHub/langium-minilogo/out/cli/index.js:39:40
   at Generator.next (<anonymous>)
   at fulfilled (/Users/stevehickman/Documents/GitHub/langium-minilogo/out/cli/index.js:5:58) {
 errno: -2,
 syscall: 'open',
 code: 'ENOENT',
 path: './src/static/mini-logo.js'
}
``

**Comment by montymxb** [comment]
@steve-hickman-epistimis thanks for the catch! Looks like I introduced this bug when I was rewriting things, and subsequently was on vacation for a bit.

I just pushed a commit up a moment ago that should rectify this, but I'll wait to hear from you that it's working as expected.

**Comment by montymxb** [comment]
Closing as resolved by commit https://github.com/langium/langium-minilogo/commit/79406874b705099ac61f638214a21c6ccbda2ce4
