### ISSUE TITLE
Update to 1.0

### ISSUE THREAD

**Issue by cdietrich** [langium/langium-minilogo#4]
Hi, it would be nice if the tutorial can be updated to 1.0
constructs like
https://github.com/langium/langium-minilogo/blob/79406874b705099ac61f638214a21c6ccbda2ce4/src/language-server/minilogo-validator.ts#L8
wont work there anymore

**Comment by montymxb** [comment]
Thanks for bringing this up @cdietrich . We should definitely update this to work with the most recent Langium release. I would be happy to put some time aside to update this repo to the new spec, when I get a moment. We should also update the tutorials pages as well based on the diffs. I'll assign myself to tackling this in the meantime.

**Comment by montymxb** [comment]
@cdietrich updated this example to use Langium 1.0.1 a couple weeks ago. Closing this out as resolved in the meantime.
